#!/usr/bin/env bash

sudo yabai --load-sa
#yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
# ====== Variables =============================

gaps_top="30"
gaps_bottom="2"
gaps_left="2"
gaps_right="2"
gaps_inner="2"


# ====== Tiling settings =======================

# 使用 font-awesome 替代罗马数字

yabai -m config status_bar_position top

yabai -m config layout                      bsp
#yabai -m config layout                         float

# bar settings

#yabai -m config top_padding                 "${gaps_top}"
yabai -m config bottom_padding              "${gaps_bottom}"
yabai -m config left_padding                "${gaps_left}"
yabai -m config right_padding               "${gaps_right}"
yabai -m config window_gap                  "${gaps_inner}"

yabai -m config mouse_follows_focus         off
yabai -m config focus_follows_mouse         off

yabai -m config mouse_modifier              fn
yabai -m config mouse_action1               move
yabai -m config mouse_action2               resize

yabai -m config window_topmost              off
yabai -m config window_opacity              off
yabai -m config window_shadow               float

yabai -m config active_window_opacity       1.0
yabai -m config normal_window_opacity       0.8
yabai -m config split_ratio                 0.5
yabai -m config auto_balance                off

# ====== Border settings =======================

yabai -m config window_border on
yabai -m config window_border_width         4
yabai -m config active_window_border_color   0xff775759


# ====== List of rules =========================


yabai -m rule --add label=safari app="^Safari$" space=1
yabai -m rule --add label=iTerm2 app="^iTerm$" space=1

#yabai -m rule --add label=chrome app="^Google Chrome$" space=2
yabai -m rule --add label=vscode app="^Code$" space=2

#yabai -m rule --add label=wechat app="^ 微信 $" space=3
#yabai -m rule --add label=qq app="^ 微信" space=3

#yabai -m rule --add label=musicapp app="^Music$" space=4
#yabai -m rule --add label=musicapp app="网易云音乐" space=3

#yabai -m rule --add label=iina app="^IINA$" space=4

# yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off border=off

# 临时性的App 也就是manage=off不受到yabai平铺式的限制，之前怎么弹出来就怎么弹出来
otherApp='^(IINA|访达|Calendar|网易云音乐|日历|System Preferences|系统偏好设置|1Password 7|Mail|QQ)$'
yabai -m rule --add app="${otherApp}" manage=off
